Add contact form to portfolio
Kwamay/Porfolio_Setup_Project pull request #4
Opened 2023-06-13 17:56 UTC by Kwamay

-[ ] Added contact form to index.html
-[ ] Added contact styles to style.css
-[ ] Added formspree to contact form

2023-06-13 18:32 UTC, Shisui6 requested changes
Hi @Kwamay, 

# Requires Changes 🍀
You have done a great job so far!👏👏
You still need to work on a few issues before moving on to the next project, but you're almost there🪲!

## Highlights🎯
- Form validations added ✅
- Good design ✅


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🪶
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-13 18:32 UTC, Shisui6 commented on style.css
> +  background-image: url(images/2nd-phase/contact-bg.png);
Your background image is currently not showing in the browser. Please check that your URL is correct so that the image shows in order to match the figma design🙏

<img width="219" alt="image" src="https://github.com/Kwamay/Porfolio_Setup_Project/assets/37116322/961324c5-13ae-4257-a0db-45cba260478a">

2023-06-13 18:32 UTC, Shisui6 commented on style.css
> +}
Kindly centralize your contact form paragraph to adhere to the figma design🙏

2023-06-13 18:32 UTC, Shisui6 commented on style.css
> +
Your form elements seem to be causing a lot of extra horizontal whitespace in your design. Consider modifying the top of your CSS file to include the following code in order to eliminate the whitespace and make your design match the figma design

```
* {
  box-sizing: border-box;
}

body {
  margin: 0;
  padding: 0;
  font-family: "Poppins", sans-serif;
}

```

Your design:
<img width="237" alt="image" src="https://github.com/Kwamay/Porfolio_Setup_Project/assets/37116322/fe6fdb26-d6d2-4c21-802e-a05c40bd6203">

Figma design:
<img width="213" alt="image" src="https://github.com/Kwamay/Porfolio_Setup_Project/assets/37116322/81553028-922e-4f12-8d3e-0cd04aa70e61">

2023-06-14 13:23 UTC, wayungi requested changes
Hi @Kwamay , 

![image](https://user-images.githubusercontent.com/99656687/234200054-89d3fce4-7f5b-4e07-a92f-9fad90948091.png)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
- [ ] All linter checks passing ✔️ 
- [ ]  Correct GitHub flow ✔️ 
- [ ] Descriptive PR body 

 ## Required Changes ♻️
_Check the comments under the review._

- [x] Please, position your background image correctly so that it does not overlap with the texts on the page as seen below. A good background image must not interfere with the content presented. Please use the Figma as a guide. 

![bg](https://github.com/Kwamay/Porfolio_Setup_Project/assets/99656687/6d1d2561-4dc6-4898-8efc-31b44e206ac9)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 14:31 UTC, shahadat3669 approved these changes
Hi @Kwamay @cloud007bond , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Highlights
✅Form validations added 
✅ Good PR Title
✅ Follow Github flows

## Optional suggestions
### You can consider: 
- [Optional] There seems to be a vertical scrolling issue on your webpage, which may be caused by inconsistent element widths. It's important to ensure that the layout is consistent and doesn't create unnecessary vertical scrolling. Please review and adjust the elements to remove the vertical scroll. This will enhance the user experience. 👍 

[Portfolio (1).webm](https://github.com/Kwamay/Porfolio_Setup_Project/assets/55840999/3e41bc48-a1ea-4cb9-ae7a-96267b5154c8)

- [Optional] I noticed that there are some section headings listed in the "Table of Contents" that are not available in your README file. I have marked these headings in red in the image. To maintain consistency and avoid confusion, it would be best to remove these headings from the "Table of Contents" if the corresponding sections are not present in your README file. 👍 
![image](https://github.com/Kwamay/Porfolio_Setup_Project/assets/55840999/52a0ecf7-e700-49c2-8d18-442d7c2a56f6)
- [Optional] Good job on adding the key features section to your README! However, it seems that you don't have proper key features. Kindly add a meaningful and comprehensive list of the key features of your project. This will provide readers with a clear understanding of what your project has to offer. Keep up the great work and ensure that the README accurately reflects the full set of key features in your project!

| Your | Professional |
| --- | --- |
| ![image](https://github.com/Kwamay/Porfolio_Setup_Project/assets/55840999/979580ea-0e48-49f4-9f56-ec0afef9358e) | ![image](https://github.com/Kwamay/Porfolio_Setup_Project/assets/55840999/3ea7afdd-9d5a-469a-be14-63421b3b7762) |



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-14 14:39 UTC, merged